# Generated by Django 4.2.2 on 2023-06-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=254)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parking.park')),
            ],
        ),
    ]
