# Generated by Django 4.2.2 on 2023-07-14 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='park',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Parking.parkingspace'),
        ),
        migrations.AddField(
            model_name='controller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to=settings.AUTH_USER_MODEL),
        ),
    ]
