# Generated by Django 4.2.2 on 2023-10-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reservation_id',
            field=models.IntegerField(null=True),
        ),
    ]
