# Generated by Django 4.2.2 on 2023-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=80.0, max_digits=4)),
                ('is_open', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
