# Generated by Django 4.2.2 on 2023-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='spot1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
