# Generated by Django 4.2.2 on 2023-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_parkingspace_spot1_parkingspace_spot10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
    ]
