# Generated by Django 4.2.2 on 2023-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0004_alter_parkingspace_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='spot',
            field=models.TextField(null=True),
        ),
    ]
