# Generated by Django 4.2.2 on 2023-09-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0005_reservation_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='spot11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot19',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spot20',
            field=models.BooleanField(default=False),
        ),
    ]
