# Generated by Django 4.2.2 on 2023-10-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0008_parkingspace_spot11_parkingspace_spot12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot11',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot12',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot13',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot14',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot15',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot16',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot17',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot18',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot19',
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='spot20',
        ),
    ]
